# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 77a1b08bbf3eded74f43d7defbfa46516636abf75ec2e9d8bfb1c5fa1b0114d73022908a50b0ccd47fbf3a8fe3ab16d7efa7fcadad98cc6287148c477ce9052c

test:
  secret_key_base: 6e079267bb390fcb2f128c04213876929dc3ddde22e4f5048367475b3dcf9761e4c8c525a6f1d67c90e2ae31c132ba5ec45e0e89de890adbcb8515ece8a05793

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
